### ISSUE TITLE
Question: What's the current status of JavaScript asset managers?

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#11]
Of course, within a month anything we write will be dated. :coffee:

**Comment by halfnibble** [comment]
I can't recall the answer off the top of my head, but Lightweight Django was recently published by the Caktus Group, and they delve deep into using JavaScript with Django. It's a thin book, and may be worth reading through to find the answer.

**Comment by halfnibble** [comment]
FYI, I re-read parts of Lightweight Django. It looks like they are using **django-compressor** for both JavaScript and CSS (including LESS/Sass) asset management.

**Comment by grayj** [comment]
I got tired of dealing with these, so now I use Gulp. Would definitely recommend dealing with JavaScript assets via JavaScript. Need NPM for installing assets anyway.

**Comment by dansackett** [comment]
I believe Gulp has emerged as a leading build tool. I use it for all frontend tasks and prefer keeping my backend and frontend separate. NPM for all that you can with Bower only if needed.

**Comment by treyhunner** [comment]
I always use Node-based tools to manage my JavaScript assets now.  I used to use django-compressor, but the front-end community has standardized on Node-based tools.

Gulp is more _in_ than Grunt right now because of its flexibility (piping streams is easy).  I would see Broccoli-based asset pipelines becoming more popular (it's used by ember-cli which is growing in popularity).

**Comment by gregmuellegger** [comment]
I also stick with Gulp and other NPM based tooling. Gulp is a full buildtool with pipelining, dependencies etc, where django-compressor and alternatives fall short. There is a plugin for _everything_. I also love integration with transpilers like babeljs (ES6 to ES5 transpiler) and that it's super fast.

I have a gulp command `gulp serve` that starts django's runserver, watches scss and JS files to rebuild and also provides livereload capabilites. Very easy to setup and as a developer a lot easier to grasp than Grunt.

**Comment by tBaxter** [comment]
I do it locally with codekit. Which may be grunt underneath for all I know.

**Comment by pennomi** [comment]
Gulp (and Bower), definitely. Once I stopped fighting it and started using a JavaScript build system for JavaScript, virtually all my problems went away. Django compressor was always a headache.

**Comment by ngzhian** [comment]
[webpack](http://webpack.github.io/) is quite popular as well

**Comment by bretth** [comment]
There's also a push from soem to keep things simple and use npm as the build tool exemplified by this http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

**Comment by pydanny** [comment]
How about Gulp as the lead, plus suggestions for other tools?

**Comment by driesdesmet** [comment]
Gulp seems to be in the lead, but what I'd really like are suggestions to do as pythonic as possible with django-bower and libsass based python preprocessor, if such a tool exists. I'm currently using a combination of gulp, mainly because of 'browsersync' that auto-reloads my browser even when I change django templates. But if there would be a python based solution, i'd drop gulp in a second.

I've also seen other people bringing django-compressor in the mix. Which diversifies the tools used even further.

While typing this, I noticed the original issue was 'javascript asset management' as opposed to using a complete build script. If we limit the scope to javascript asset management only, then I guess django-bower fits well. It's a wrapper around the globally installed bower npm package, but at least it fits in your workflow without adding a package.json or .bowerrc in your source code.

**Comment by pydanny** [comment]
The lack of consensus here is interesting. Either I defined the question poorly, it's changing too fast, or there is no best thing to suggest.

**Comment by pydanny** [comment]
Went with gulp.js. When the status quo changes in the near future we may switch to that. Am I being too cynical? :stuck_out_tongue_winking_eye:
