### ISSUE TITLE
Form instance attributes in Ch. 10

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.8#13]
@halfnibble said:

> I'd like to see the information in your blog post (about form instance attributes) in Ch. 10 of 2 Scoops of Django.
> I almost immediately needed to use this in an ecommerce project, and I re-read Ch. 10 of your book a couple times before I found my answer in the blog post.

**Comment by pydanny** [comment]
This would mean including content similar to http://www.pydanny.com/adding-django-form-instance-attributes.html

**Comment by pydanny** [comment]
Form code:

``` python
from django import forms

from .models import MyModel


class MyForm(forms.ModelForm):

    class Meta:
        model = MyModel

    def __init__(self, user_id, *args, **kwargs):
        super(MyForm, self).__init__(*args, **kwargs)

        # set the user_id as an attribute of the form
        self.user_id = user_id
```

**Comment by pydanny** [comment]
CBV code:

``` python
from django.views.generic import UpdateView

# this assumes that django-braces is installed
from braces.views import LoginRequiredMixin

from .forms import MyForm
from .models import MyModel


class MyUpdateView(LoginRequiredMixin, UpdateView):
    model = MyModel
    form_class = MyForm
    success_url = "/someplace/"

    def get_form_kwargs(self):
        """This method is what injects forms with their keyword
            arguments."""
        # grab the current set of form #kwargs
        kwargs = super(MyUpdateView, self).get_form_kwargs()
        # Update the kwargs with the user_id
        kwargs['user_id'] = self.request.user.pk
        return kwargs
```

**Comment by halfnibble** [comment]
Yes, that blog post. Sorry, I should have placed a link to it. :+1:

**Comment by lambacck** [comment]
I responded to the [tweet](https://twitter.com/pydanny/status/591641033613545472) about this but I think I need to expand on what I said there.

I think that the concept of passing in extra form args through `get_form_kwargs` is an important concept for getting past the most basic of form validation. In fact the specific example mentioned above is so common, it has made it into braces as [braces.views.UserFormKwargsMixin](http://django-braces.readthedocs.org/en/latest/form.html#userformkwargsmixin) and [braces.forms.UserKwargModelFormMixin](http://django-braces.readthedocs.org/en/latest/form.html#userkwargmodelformmixin) which work together to accomplish this.

A key thing to note about the example provided is that the form example could break further inheritance because the it is using user_id as the first positional argument. To properly support further cooperative multiple inheritance the `__init__` method should be:

``` py
    def __init__(self, *args, **kwargs):
        self.user_id = kwargs.pop('user_id')
        super(MyForm, self).__init__(*args, **kwargs)
```

This spelling is required because the form base classes can complain about getting extra kwargs parameters and it doesn't add anything to the method signature. This _should_ be best practice always (even if it is a top class) because a refactor that extracted some or all of the `__init__` method out into a Mixin could end up failing in surprising ways depending on inheritance order.

**Comment by lambacck** [comment]
And of course that is the same as the implementation found in braces except they provide user object instead of user_id: https://github.com/brack3t/django-braces/blob/release/braces/forms.py#L11

**Comment by pydanny** [comment]
When this gets added, we'll use an improved version of the code I listed above, passing in the object rather than the ID. We will reference django-braces as tool, but because there is too much abstraction, won't demonstrate the mixins.

**Comment by pydanny** [comment]
:ship: with special thanks to @lambacck :smile:
