### ISSUE TITLE
Complex Form Wizards

### ISSUE THREAD

**Issue by lachlansimpson** [twoscoops/two-scoops-of-django-1.8#16]
Utilising, for instance, SessionWizardView and get_context_args(), get_form_kwargs(), get_template_name() and done().

There isn't much out there on complex forms.

**Comment by halfnibble** [comment]
And now they are in a separate package! No longer part of Django proper.
https://docs.djangoproject.com/en/1.8/releases/1.8/#removal-of-django-contrib-formtools

Which has me concerned, since I use them for an integral part of client work. I hope packages moved out of Django proper still get love and attention?

**Comment by iyn** [comment]
I would also be interested in learning, if form wizards somehow works with AJAX. In my app I also have multi step form, but I wanted transitions between steps to be "smooth", so instead of using form wizard, I used jQuery Steps (https://github.com/rstaib/jquery-steps) and created 1 big Django Form for the sake of server side verification, manually rendering the form in the template. It works, but it's not really elegant and far from being what I want. Not sure if all this is in scope of the book, though.

**Comment by pydanny** [comment]
We've decided that form wizards are out of scope. That said, if I write the book I mention in #18, it makes for great material.

**Comment by lachlansimpson** [comment]
That's fair enough tbh, they can be quite complex and really are for
_advanced_ users - or at least people who are on their way to being
advanced, as I discovered.

Cheers

---

I'm treading carefully
but it's the time of night
the snowy light
the subway roar
and the whispered fights
exciting sights
but it's not enough
I thought it was
I wish it was

## I thought it was

You name it - The Cannanes with Explosion Robinson.
