### ISSUE TITLE
Custom User Model info

### ISSUE THREAD

**Issue by iyn** [twoscoops/two-scoops-of-django-1.8#17]
I think that it's worth mentioning Custom User Model, since there is no so much good info about it on the web and imo official documentation isn't very clear (I know that is was mentioned in 1.5, but it's good to update how it relates to new features, like migrations). 

[the next paragraph doesn't apply to the 1.8 version, I had this problem with 1.8b, but I'm leaving this here, because someone can have this problem either]
Also, there are issues with migrations & Custom User Model, and that was really PITA for me. Couldn't find it anywhere, but if a custom user model is referenced in another model/app (e.g in a `ForeignKey`), initial migration file needs to have dependency entry for Custom User Model. Say, I have a model `Account` as a Custom User Model, and in another app, say "orders", I want to add `ForeignKey` to `Account`. `./manage.py makemigrations` generates initial migration file, but without adding:
`dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL)
    ]
`
there will be a lot of problems later with migrations/db. Testing also will be broken (since new db has to be created and migrations will fail).

Anyway, I loved 2SCOF1.5, can't wait to read the 1.8 book :)

**Comment by iyn** [comment]
OK, just tried to reproduce this bug with migrations with the latest version and it works as expected (I started project with 1.8b, this could be the reason). But still, I think it'd be good to include some info about Custom User Model and maybe using custom auth backends (e.g for Facebook login)

**Comment by pydanny** [comment]
@iyn First, thanks for the suggestion! Now let's discuss your requests:

On custom User models: In TSD1.6 we added some material on custom user models. Most of that will be coming over.

On custom auth backends: We don't cover custom auth backends in any kind of depth because we point tools like `django-allauth`, `python-social-auth`, `django-twofactor-auth` et al. In fact, the big recommendation we can add is to use those instead of rolling your own because having more eyes on keeping up with often-changing-OAUTH-implementations is a good idea. That said, if your app is 100% dedicated to working on just one platform (i.e. making an app that is 100% only on Facebook, Eventbrite, et al), then rolling your own or finding a specific library can be useful.

**Comment by iyn** [comment]
@pydanny sorry, I didn't read 1.6.

In fact, I'm using django-allauth in my apps, I was suggesting mentioning custom for the sake of deeper understanding Django. But I totally understand your point of view. Anyway, thank you for being responsive :+1:

**Comment by pydanny** [comment]
Re-opening so we remember to add something on the lines of "That said, if your app is 100% dedicated to working on just one platform (i.e. making an app that is 100% only on Facebook, Eventbrite, et al), then rolling your own or finding a specific library can be useful."
