### ISSUE TITLE
Form validation code

### ISSUE THREAD

**Issue by arnaudlimbourg** [twoscoops/two-scoops-of-django-1.8#63]
Hello,

Examples showing form validation use the following form:
`raise forms.ValidationError(msg)`

[According to the documentation](https://docs.djangoproject.com/en/1.8/ref/forms/validation/#raising-validationerror) a "code" parameter should be used, the documentation is bit inconsistent though as the examples that follow don't use one.

It might make sense to update the examples to use a form with a code:
`raise forms.ValidationError(msg, code='invalid')`

**Comment by pydanny** [comment]
Digging into the code, it is unfortunately not very clear why and how Django may or may not make use of the code argument in Forms.ValidationError.

**Comment by pydanny** [comment]
Mark Lavin pointed out https://github.com/django/django/blob/1.8.1/django/forms/models.py#L398, which upon further research allows some interesting work done with Form error messages. https://docs.djangoproject.com/en/1.8/ref/forms/fields/#error-messages

Also, the use case for this is possibly for overriding model error messages with form-level error messages, which is done on a case-by-case practice. The problem is that we haven't played with this feature yet. Therefore, not sure this is going to be able to be gotten in on time. 

Better to leave something out then to do it badly, right? ;)

**Comment by pydanny** [comment]
One more thing, I'm not sure attaching these codes to ValidationErrors is what I would consider a 'best practice'. It bears more research.

**Comment by pydanny** [comment]
According to @mjtamlyn it is used to identify errors, to programmatically check errors: https://gist.github.com/mjtamlyn/00a34acb07481d8ae28d

This won't be added in update #3. Need more time to consider it.

**Comment by pydanny** [comment]
Also part of https://github.com/django/django/pull/4645

**Comment by mjtamlyn** [comment]
On a personal note, I feel that Django's docs are maybe a little heavy handed with recommending they use of `code` as a best practice everywhere, although it should be encouraged in third party applications. It is however definitely the best practice for any situation where you wish to check the nature of the errors - it's much better than checking the message of the validation error as this is subject to copy changes.

**Comment by arnaudlimbourg** [comment]
That makes sense, as @mjtamlyn is saying the documentation does recommend it a lot so even if I wasn't sure how it would impact things it seemed sensible to follow the documentation :)

**Comment by audreyfeldroy** [comment]
I put in a tip box about it, right after that particular form validation example. Didn't go into much detail; just pointed it out, linked to the guideline, and quoted @mjtamlyn. Thank you @arnaudlimbourg and @mjtamlyn :ship:
